language: objective-c

before_install: 
 - wget "http://download.mono-project.com/archive/3.2.0/macos-10-x86/MonoFramework-MDK-3.2.0.macos10.xamarin.x86.pkg"
 - ls -l
 - sudo installer -pkg MonoFramework-MDK-3.2.0.macos10.xamarin.x86.pkg -target /
 - wget "http://nodejs.org/dist/v0.10.28/node-v0.10.28.pkg"
 - ls -la
 - sudo installer -pkg node-v0.10.28.pkg -target /
 - npm install

script:
 - ./nunit.sh
 - npm test

after_success: ./somee.sh

